
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-19T15:18:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a5f3ac86ac14585a7fe6b182b8f811c85de06e8",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
